#!/bin/bash

# Nombre del proyecto
project_name="SRR2052337"

# Directorio de instalación para herramientas
tools_dir="./tools"

# Verificar si el SRA Toolkit está instalado
if ! command -v prefetch &> /dev/null; then
    echo "SRA Toolkit no está instalado. Iniciando la instalación en $tools_dir..."
    
    # Descargar e instalar SRA Toolkit
    mkdir -p "$tools_dir"
    cd "$tools_dir"
    
    wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-centos_linux64.tar.gz
    tar -xzf sratoolkit.current-centos_linux64.tar.gz
    export PATH=$PATH:"$tools_dir/sratoolkit.current-centos_linux64/bin"
    
    echo "SRA Toolkit instalado correctamente."
    
    # Regresar al directorio original
    cd -
fi

# Verificar si FastQC está instalado
if ! command -v fastqc &> /dev/null; then
    echo "FastQC no está instalado. Iniciando la instalación en $tools_dir..."
    
    # Descargar e instalar FastQC
    cd "$tools_dir"
    wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip
    unzip fastqc_v0.11.9.zip
    chmod +x FastQC/fastqc
    export PATH=$PATH:"$tools_dir/FastQC"
    
    echo "FastQC instalado correctamente."
    
    # Regresar al directorio original
    cd -
fi

# Directorio de descarga para el proyecto
download_dir="./$project_name"

# Crear el directorio de descarga si no existe
mkdir -p "$download_dir"

# Descargar el conjunto de datos del proyecto
prefetch --max-size 100G -O "$download_dir" $project_name

# Convertir a formato FASTQ (opcional)
fastq-dump --split-files -O "$download_dir" $project_name

# Borrar el archivo original después de la conversión
rm "$download_dir/$project_name.sra"

# Generar informes de calidad con FastQC
fastqc -o "$download_dir" "$download_dir"/*.fastq


